; PlatformIO Project Configuration File

[env:airm2m_core_esp32c3]
platform = espressif32
board = airm2m_core_esp32c3
framework = espidf
monitor_speed = 115200
build_unflags = -fuse-cxa-atexit
board_build.partitions = partitions.csv
extra_scripts =
    pre:build_spiffs.py

lib_deps =
    lvgl/lvgl @ ^9.5.0

lib_ignore =
    lvgl
